project:
  type: website
  output-dir: docs

include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "images/favicon.png" />

website:
  title: "pathogensurveillance documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quickstart
      - href: documentation.qmd
        text: Documentation
      - href: tutorial.qmd
        text: Tutorial
      - href: examplereports.qmd
        text: Example Reports
      - href: citations.qmd
        text: Citations
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



