---
title: "Citations"
editor: visual
bibliography: references.bib
nocite: |
  @*
---

## Credits {#credits}

nf-core/pathogensurveillance was written by:

[Zachary S. L. Foster](https://orcid.org/0000-0002-5075-0948)^1^, [Martha Sudermann](https://orcid.org/0000-0001-6912-3461)^2^, [Camilo Parada-Rojas](https://orcid.org/0000-0002-8372-6012)^2^, [Fernanda Iruegas-Bocardo](https://scholar.google.com/citations?user=JIc7VPUAAAAJ&hl=en)^2^, [Ricardo Alcalá-Briseño](https://orcid.org/0000-0002-7031-2195)^2^, [Logan K. Blair](https://scholar.google.com/citations?user=6pnLWcAAAAAJ&hl=en&oi=ao) ^1^, [Alexandra J Weisberg](https://orcid.org/0000-0002-0045-1368)^2^, [Jeff H. Chang](https://orcid.org/0000-0002-1833-0695)^2^, and [Niklaus J. Grünwald](https://orcid.org/0000-0003-1656-7602)^1^

^1^Horticultural Crops Research Laboratory, USDA Agricultural Research Service, Corvallis, Oregon 97331, USA

^2^Department of Botany and Plant Pathology, Oregon State University, Corvallis, Oregon 97331, USA

<!-- TODO nf-core: If applicable, make list of people who have also contributed -->

## Contributions and Support {#contributionsandsupport}

If you would like to contribute to this pipeline, please see the [contributing guidelines](.github/CONTRIBUTING.md).

For further information or help, don't hesitate to get in touch on the [Slack `#pathogensurveillance` channel](https://nfcore.slack.com/channels/pathogensurveillance) (you can join with [this invite](https://nf-co.re/join/slack)).

## Citations {#citations}

<!-- TODO nf-core: Add citation for pipeline after first release. Uncomment lines below and update Zenodo doi and badge at the top of this file. -->

<!-- If you use  nf-core/pathogensurveillance for your analysis, please cite it using the following doi: [10.5281/zenodo.XXXXXX](https://doi.org/10.5281/zenodo.XXXXXX) -->

<!-- TODO nf-core: Add bibliography of tools and data used in your pipeline -->

Note: these citations are for all possible programs that may be used by pathogensurveillance. The final report will only present citations of programs used in the current run.

::: {#refs}
:::
